```yaml
services:
  app:
    build:
      context: .
    restart: unless-stopped
    init: true
    environment:
      - PYTHONPATH=/app
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
networks:
  default:
    driver: bridge
```