version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server_container
    ports:
      - "5000:5000"
    networks:
      - app_network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client_container
    depends_on:
      - server
    networks:
      - app_network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
