version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - app-net
    expose:
      - "65432"
    command: ["python3", "server.py"]

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client_app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    depends_on:
      - server
    networks:
      - app-net
    command: ["python3", "client.py", "server", "65432"]  # <-- подключение по имени сервиса

networks:
  app-net:
    driver: bridge
